# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 382)
        MainWindow.setStyleSheet("background-color: rgb(240, 248, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 237, 77))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 100, 100);")
        self.label.setObjectName("label")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(104, 150, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.play_btn.setFont(font)
        self.play_btn.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.play_btn.setObjectName("play_btn")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 210, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.time_btn = QtWidgets.QPushButton(self.centralwidget)
        self.time_btn.setGeometry(QtCore.QRect(100, 270, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.time_btn.setFont(font)
        self.time_btn.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.time_btn.setObjectName("time_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Судоку"))
        self.play_btn.setText(_translate("MainWindow", "Играть"))
        self.pushButton_4.setText(_translate("MainWindow", "Правила"))
        self.time_btn.setText(_translate("MainWindow", "Статистика"))
