# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 368)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 237, 77))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 100, 100);")
        self.label.setObjectName("label")
        self.easy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.easy_btn.setGeometry(QtCore.QRect(100, 130, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.easy_btn.setFont(font)
        self.easy_btn.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.easy_btn.setObjectName("easy_btn")
        self.medium_btn = QtWidgets.QPushButton(self.centralwidget)
        self.medium_btn.setGeometry(QtCore.QRect(100, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.medium_btn.setFont(font)
        self.medium_btn.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.medium_btn.setObjectName("medium_btn")
        self.play_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn_3.setGeometry(QtCore.QRect(100, 270, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.play_btn_3.setFont(font)
        self.play_btn_3.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.play_btn_3.setObjectName("play_btn_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Играть"))
        self.easy_btn.setText(_translate("MainWindow", "Легко"))
        self.medium_btn.setText(_translate("MainWindow", "Средне"))
        self.play_btn_3.setText(_translate("MainWindow", "Сложно"))
