# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 288, 77))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 100, 100);")
        self.label.setObjectName("label")
        self.rules = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rules.setGeometry(QtCore.QRect(50, 100, 411, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rules.setFont(font)
        self.rules.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(0, 100, 100);")
        self.rules.setObjectName("rules")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Правила"))
        self.rules.setPlainText(_translate("MainWindow", "Игровое поле представляет собой квадрат, разделённый на меньшие квадраты. Уже в начале игры стоят некоторые числа (от 1 до 9), называемые подсказками. Требуется заполнить свободные клетки цифрами от 1 до 9 так, чтобы в каждой строке, в каждом столбце и в каждом малом квадрате 3×3 каждая цифра встречалась бы только один раз.\n"
"Сложность зависит от количества изначально заполненных клеток. \n"
"Головоломка имеет только одно решение. "))
